project: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/QC
manifest: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/Manifest/SR0443-004-ANALYSIS-MANIFEST.csv
exomCQA_gene: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/QC/Breast_gene.chrALL
exomCQA_exon: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/QC/Breast_exon.chrALL
precalling_report: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/QC/pre_calling_qc_report.txt
doc_template_germline: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/QC/ExomeQcPipeline/ExomeQcPipeline_Template_interim.docx
doc_template_somatic: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/QC/ExomeQcPipeline/ExomeQcPipeline_Template_interim.docx
ref: /DCEG/CGF/Resources/Data/genome/hg19_canonical_correct_chr_order.fa
capturekit: /DCEG/Projects/Exome/SequencingData/BED_FILES/customized_capturekit/161006_HG19_Kid-Lung-Extra_EZ_HX3_primary_targets.bed
#/DCEG/Projects/Exome/SequencingData/BED_FILES/NV3UTR_NV3_nopadding_corrected.bed
population_file: modules/HGDP/example.id #NA when no population file can be provided

ensemble_vcf: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/Results/annotation/merged_ensemble_voting_passed_annotated.vcf
ensemble_dir: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/Results/Ensemble
bam_location: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/bam_location

somatic: TRUE
BamMatcher: ~/tools/bam-matcher/bam-matcher.py
pairs: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/Manifest/pairs.txt

ancestry_check: TRUE
bam-matcher_check: TRUE
contamination_check: TRUE
coverage_check: TRUE
duplication_check: TRUE
exomeCQA_check: TRUE
gender_check: TRUE
pre_calling_check: TRUE
postcalling_check: TRUE