##general required files
project: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/QC
manifest: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/Manifest/SR0443-004-ANALYSIS-MANIFEST_test.csv
bam_location: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/bam_location
precalling_report: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/QC/pre_calling_qc_report.txt
ref: /DCEG/CGF/Resources/Data/genome/hg19_canonical_correct_chr_order.fa
capturekit: /DCEG/Projects/Exome/SequencingData/BED_FILES/customized_capturekit/161006_HG19_Kid-Lung-Extra_EZ_HX3_primary_targets.bed
#/DCEG/Projects/Exome/SequencingData/BED_FILES/NV3UTR_NV3_nopadding_corrected.bed

population_file: modules/HGDP/example.id #NA when no population file can be provided
MODE: somatic # wgs,wes, somatic
tmpDir: /scratch/fz32402_qc

##germline required files
ensemble_vcf: 
doc_template_germline: ExomeQcPipeline_Template_interim.docx

##somatic required files
BamMatcher: /DCEG/CGF/Bioinformatics/Production/software/bam-matcher/bam-matcher3.py
pairs: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/Manifest/pairs_test.txt
doc_template_somatic: ExomeQcPipeline_Somatic_Template_interim.docx
ensemble_dir: /DCEG/Projects/Exome/builds/build_SR0443-004_somatic_UMI_25938/Results/Ensemble

##flags
post_calling_check: TRUE
relatedness_check: FALSE

##parameter files
##fastNGSsite: /CGF/Bioinformatics/Production/Wen/20210208_hongkongbreast_wgs/ref_1000G/shapeit2_integrated_v1a.GRCh38.20181129.phased.plink_chr.sites
##fastNGSpanel: /CGF/Bioinformatics/Production/Wen/20210208_hongkongbreast_wgs/ref_1000G/refPanel_shapeit2_integrated_v1a.GRCh38.20181129.phased.plink.txt
##fastNGSiInd: /CGF/Bioinformatics/Production/Wen/20210208_hongkongbreast_wgs/ref_1000G/nInd_shapeit2_integrated_v1a.GRCh38.20181129.phased.plink.txt
##refPlink: /CGF/Bioinformatics/Production/Wen/data1000genomes/shapeit2_integrated_v1a.GRCh38.20181129.phased.plink
##refPlinkFam: /CGF/Bioinformatics/Production/Wen/data1000genomes/shapeit2_integrated_v1a.GRCh38.20181129.phased.plink.fam
fastNGSsite: /DCEG/CGF/Bioinformatics/Production/software/fastNGSadmix/data1000genomes/1000genomesRefPanel_chr.sites
fastNGSpanel: /DCEG/CGF/Bioinformatics/Production/software/fastNGSadmix/data1000genomes/refPanel_1000genomesRefPanel.txt
fastNGSiInd: /DCEG/CGF/Bioinformatics/Production/software/fastNGSadmix/data1000genomes/nInd_1000genomesRefPanel.txt
refPlink: /DCEG/CGF/Bioinformatics/Production/software/fastNGSadmix/data1000genomes/1000genomesRefPanel
refPlinkFam: /DCEG/CGF/Bioinformatics/Production/software/fastNGSadmix/data1000genomes/1000genomesRefPanel.fam
omniVcf: /DCEG/CGF/Bioinformatics/Production/Wen/git/VerifyBamID/resource/exome/1000g.phase3.10k.b37.exome.vcf.gz
bamMatcherVcf: /DCEG/CGF/Bioinformatics/Production/software/bam-matcher/1kg.exome.highAF.7550.vcf

#
#fastNGSsite: /DCEG/CGF/Bioinformatics/Production/Wen/20210208_hongkongbreast_wgs/ref_1000G/shapeit2_integrated_v1a.GRCh38.20181129.phased.plink_chr.sites
#fastNGSpanel: /DCEG/CGF/Bioinformatics/Production/Wen/20210208_hongkongbreast_wgs/ref_1000G/refPanel_shapeit2_integrated_v1a.GRCh38.20181129.phased.plink.txt
#fastNGSiInd: /DCEG/CGF/Bioinformatics/Production/Wen/20210208_hongkongbreast_wgs/ref_1000G/nInd_shapeit2_integrated_v1a.GRCh38.20181129.phased.plink.txt
#refPlink: /DCEG/CGF/Bioinformatics/Production/Wen/data1000genomes/shapeit2_integrated_v1a.GRCh38.20181129.phased.plink
#refPlinkFam: /DCEG/CGF/Bioinformatics/Production/Wen/data1000genomes/shapeit2_integrated_v1a.GRCh38.20181129.phased.plink.fam
#omniVcf: /DCEG/CGF/Bioinformatics/Production/Wen/git/VerifyBamID/resource/exome/1000g.phase3.10k.b38.exome.vcf.gz
#bamMatcherVcf:/DCEG/CGF/Bioinformatics/Production/Dongjing/bam-matcher/download_1kg.exome.highAF.7550.hg38.chr.vcf

