#!/usr/bin/python
#import glob
import sys
import os
from glob import glob
from scripts.utils import initializeConfigVariables

manifest, project, version, GROUPS, SAMPLES, sampleGroupDict, refFile, getBam = initializeConfigVariables(config)

rule myfastqc:
    input:
        getBam
    output:
        project + '/fastqc/{sample}_fastqc.html'
    params:
        outdir = project + '/fastqc',
        tmpdir = config['tmpDir']
    shell:
        '. /etc/profile.d/modules.sh; module load fastqc;'
        'fastqc -o {params.outdir} -f bam {input} -d {params.tmpdir}'

rule multiqc:
    input:
        expand(project + '/fastqc/{sample}_fastqc.html', sample = SAMPLES)
    output:
        project + '/fastqc/multiqc_report.html'
    params:
        outdir = project + '/fastqc'    
    singularity: "docker://ewels/multiqc:latest"
    shell:
        #'. /etc/profile.d/modules.sh; module load python/2.7.8;'
        'cd {params.outdir}; multiqc -d --force -s .'

