#!/usr/bin/python
#import glob
import sys
import os
from glob import glob
from scripts.utils import initializeConfigVariables

manifest, project, version, GROUPS, SAMPLES, sampleGroupDict, refFile, getBam = initializeConfigVariables(config) 
sex_check_dir = project + 'sex_check'

# rule all:
   # input:
       # sex_check_dir + '/sex_check.png'
       
# sex_check_dir = 'sex_check'    
# SAMPLES=[]

# for bam in glob.iglob(bam_location + '/*/*.bam', recursive=True):
    # samp = os.path.basename(bam)[:-4]
    # SAMPLES.append(os.path.basename(bam)[:-4])

rule XYratio_single:
    input:
        getBam
    output:
        project + '/sex_concordance_check/intermediate_files/counts/{sample}_X_Y_COUNTS.txt' 
    shell:
        'module load samtools;'
        'Xcount=$(samtools view -c {input} chrX );'
        'Ycount=$(samtools view -c {input} chrY );'
        'echo -e "{wildcards.sample}\t${{Xcount}}\t${{Ycount}}" > {output}'
   
rule XYratio_table:
    input:
        single = expand(project + '/sex_concordance_check/intermediate_files/counts/{sample}_X_Y_COUNTS.txt', sample = SAMPLES),
        Manifest = manifest
    output:
        sex_check_dir + '/XYratio_table.txt'
    params:
#        Manifest = getManifest, get error message of 'generator' object is not subscriptable, when use this function at params.
        merged_table = sex_check_dir + '/XYratio_merged.txt'
    run:
        with open(params.merged_table, 'w') as mergedfile:
            for fname in input.single:
                with open(fname) as infile:
                    for line in infile:
                        mergedfile.write(line)
        mergedfile.close()
        sexDic = {}
#        with open(params.Manifest[0], 'r') as manifest: get errors of read just the first letter of the path, turn out only input is list, params is suppose to be string and don't need to add [0]
        with open(input.Manifest, 'r') as manifest:
            next(manifest)
            for line in manifest:
               key = line.split(',')[6] + '_' + line.split(',')[12]
               sexDic[key] = (line.split(',')[8],line.split(',')[9])
        with open(params.merged_table, 'r') as infile, open(output[0], 'w') as outfile:
            outfile.write( 'SAMPLE\tChrX\tChrY\tREPORT_SEX\tIDENTIFILER_SEX\tYXratio' + '\n' )
            for line in infile:
                ratio = float(line.split('\t')[2])/float(line.split('\t')[1])
                value = sexDic.get(line.split('\t')[0].strip())
                if value is not None:
                    outfile.write(line.strip() + '\t' + "\t".join([str(i) for i in value]).replace("F","Female").replace("M","Male").replace("N","Unknown") + '\t' + str(ratio) + '\n')

rule sex_plot:
    input:
        sex_check_dir + '/XYratio_table.txt'
    output:
        png_sex = sex_check_dir + '/sex_check.png',
        png_self_sex = sex_check_dir + '/sex_self_check.png',
        outlier_table = sex_check_dir + '/sex_outlier.txt',
        R = sex_check_dir + '/sex_check.R',
        Rout = sex_check_dir + '/sex_check.R.out'
    run:
        rTxt = '''
        library(ggplot2)
        library(dplyr)
        data_sex <- read.table("''' + str(input) + '''", header = TRUE, sep = "\t")
        options(bitmapType='cairo')
        png("''' + str(output.png_sex) + '''", 6.5, 6.5, "in", res = 300)
        colors <- c("Male"=rgb(0, 0, 1, .3), "Unknown"=rgb(1, 0, 0, .3), "Female"=rgb(0, 1, 0, .3),"Other"=rgb(.75, .75, .75, .3) )
        sortData <- arrange(data_sex, IDENTIFILER_SEX, YXratio)
        maledata1 <- subset(sortData, IDENTIFILER_SEX=="Male", select=YXratio)
        femaledata1 <- subset(sortData, IDENTIFILER_SEX=="Female", select=YXratio)

        gg <- ggplot(sortData, aes(x=factor(SAMPLE, levels=unique(SAMPLE)), y=YXratio)) 
        gg + geom_point(aes(color=as.factor(IDENTIFILER_SEX))) + 
        scale_color_manual(name="Sex",values=colors) + 
        labs(x = "subjects", y = "ChrY/ChrX Reads Ratio") +
        theme(legend.position=c(0.1, 0.9),axis.text.x=element_blank(),axis.ticks.x=element_blank())+
        theme(axis.line = element_line(size = 1, colour = "grey"),panel.background = element_rect(fill = "white")) +
        geom_hline(yintercept = colMeans(femaledata1)+sd(femaledata1$YXratio), color=rgb(0, 1, 0, .3)) +
        geom_hline(yintercept = colMeans(maledata1)-sd(maledata1$YXratio),color=rgb(0, 0, 1, .3))

        png("''' + str(output.png_self_sex) + '''", 6.5, 6.5, "in", res = 300)
        sortData <- arrange(data_sex, REPORT_SEX, YXratio)
        maledata2 <- subset(sortData, REPORT_SEX=="Male", select=YXratio)
        femaledata2 <- subset(sortData, REPORT_SEX=="Female", select=YXratio)

        gg <- ggplot(sortData, aes(x=factor(SAMPLE, levels=unique(SAMPLE)), y=YXratio))
        gg + geom_point(aes(color=as.factor(REPORT_SEX))) +
        scale_color_manual(name="Sex",values=colors) +
        labs(x = "subjects", y = "ChrY/ChrX Reads Ratio") +
        theme(legend.position=c(0.1, 0.9),axis.text.x=element_blank(),axis.ticks.x=element_blank())+
        theme(axis.line = element_line(size = 1, colour = "grey"),panel.background = element_rect(fill = "white")) +
        geom_hline(yintercept = colMeans(femaledata2)+sd(femaledata2$YXratio), color=rgb(0, 1, 0, .3)) +
        geom_hline(yintercept = colMeans(maledata2)-sd(maledata2$YXratio),color=rgb(0, 0, 1, .3))
        
        outlier <- subset(sortData, IDENTIFILER_SEX=="Male"&YXratio<=colMeans(femaledata1)+sd(femaledata1$YXratio)|IDENTIFILER_SEX=="Female"&YXratio>=colMeans(maledata1)-sd(maledata1$YXratio)|REPORT_SEX=="Male"&YXratio<=colMeans(femaledata2)+sd(femaledata2$YXratio)|REPORT_SEX=="Female"&YXratio>=colMeans(maledata2)-sd(maledata2$YXratio))
        sink("''' + str(output.outlier_table) + '''")
        print(outlier[,c(1,4,5,6)])
        sink()      
        '''
        with open(output.R, 'w') as R:
            R.write(rTxt)
        shell('R --vanilla < {output.R} > {output.Rout}')
        
